# Generated by Django 4.0.6 on 2022-08-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageMetadata',
        ),
    ]
