# Generated by Django 4.0.6 on 2022-08-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_other'),
    ]

    operations = [
        migrations.DeleteModel(
            name='other',
        ),
    ]
